version: '3.4'
services:
    phpmyadmin:
        image: phpmyadmin
        environment:
            - PMA_ARBITRARY=1
        ports:
            - 8080:80
        networks:
            - frontend-network
            - backend-network
        depends_on: 
            - mysql
        restart: always
    mysql:
        image: mysql:5.7
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - backend-network
        restart: always
    prestashop:
        image: prestashop/prestashop
# Deshabilitamos los puertos ya que ahora van a depender del nuevo servicio
        #ports:
        #    - 80:80
        environment:
            - DB_SERVER=${DB_SERVER}
        volumes:
            - prestashop_data:/var/www/html
        networks:
            - frontend-network
            - backend-network
        restart: always
        depends_on: 
            - mysql
# Añadimos la imagen para este nuevo servcio
    https-portal:
        image: steveltn/https-portal:1
        ports:
            - 80:80
            - 443:443
        restart: always
        environment:
          DOMAINS: 'azmanishop.sytes.net -> http://prestashop:80'
          STAGE: 'production' # Don't use production until staging works
                  # FORCE_RENEW: 'true'
        networks:
            - frontend-network
networks:
    frontend-network:
    backend-network:

volumes:
    mysql_data:
    prestashop_data: